### ISSUE TITLE
Unable to use WeeChat's secured data to store token

### ISSUE THREAD

**Issue by seschwar** [mumixam/weechat-twitch#11]
This script tells me to set the Twitch API OAuth2 token like this:

```
/set plugins.var.python.twitch.token (token from url)
```

However I don't like having that token in plain text in my configuration. Therefore I tried storing it using WeeChat's [secured data](https://weechat.org/files/doc/stable/weechat_user.en.html#secured_data):

```
/set plugins.var.python.twitch.token ${sec.data.twitch}
```

However apparently secured data can only be used in options which are explicitly set to be evaluated. It seems that `plugins.var.python.twitch.token` is not among them.

Would it be possible to evaluate that option, so that secured data could be used there? Alternatively could the script read `irc.server.X.password` where `X` is in `plugins.var.python.twitch.server`?

**Comment by seschwar** [comment]
Already fixed by b9ab44d3fbd263bf0e7b4cfafba3e8ce5339d6dd.

**Comment by Mrfiregem** [comment]
This still doesn't seem to be present in the version downloaded by `/script install twitch.py`, sadly.
