### ISSUE TITLE
=!= twitch.py: error communicating with twitch api

### ISSUE THREAD

**Issue by Techman** [mumixam/weechat-twitch#4]
Hello,

I'm receiving a lot of errors with this script recently, and I reinstalled and the issue still persists. I even tried registering my own client ID on Twitch thinking that maybe the app has reached its resource limit or something, but nope.

When trying to enable debugging, I managed to crash weechat so I'm not tempted to do it again.

**Comment by mumixam** [comment]
After speaking to techman- on irc we finally discovered this issue was related to ssl/tls verify in curl. Commit https://github.com/mumixam/weechat-twitch/commit/20ab70c5478aa19d868f70f84617d6e92c8d95da adds a option to be able to disable ssl/tls verification.

**Comment by mumixam** [comment]
Do you have debug mode on?
```/set plugins.var.python.twitch.debug on```
to enable debug mode

**Comment by kossmikman** [comment]
I don't know if it's related or anything, but i 've been getting twitch api error constantly for the last few months:
`twitch.py: Error with twitch API (data key missing from json) `
I have debug mode on. I tried enabling/disabling the ssl/tls verification, but to no avail.

**Comment by mumixam** [comment]
@kossmikman are you running the latest commit from github of the script? twitch pushed some changes that require a oauth token for all api calls now. i havent got around to pushing the update to the weechat repos yet

**Comment by kossmikman** [comment]
I'm running the weechat repos, i'll check it out with the latest script.

**Comment by kossmikman** [comment]
It's fixed in the latest script, thanks.

**Comment by Techman** [comment]
I'll be honest, this issue slipped into the back of my mind. I didn't know it was still open. I run the weechat repo version of the script, so I guess I will have to wait until then :)

**Comment by kapiorr** [comment]
still have a problem
weechat 3.0-dev
twitch.py latest from github.
On connect to channel:
`twitch.py: exception: Expecting value: line 1 column 1 (char 0
 twitch.py: Error with twitch API (data key missing from json)
 twitch.py: {"error":"Unauthorized","status":401,"message":"OAuth token is missing"}`

**Comment by mumixam** [comment]
@kapiorr is  `plugins.var.python.twitch.token` set and valid?

**Comment by kapiorr** [comment]
No, I didnt known about that. How I can do this?

**Comment by mumixam** [comment]
@kapiorr try this
https://mumixam.github.io/weechat_twitch/

**Comment by kapiorr** [comment]
Everything works fine. Thanks a lot.

**Comment by Techman** [comment]
I am going to close this, because I forgot I had it open. I haven't had an issue with the script for a while.

Thank you to all who assisted me.
